CREATE TABLE PUBLIC.DOMICILIOS
(
  ID INTEGER NOT NULL,
  DESCRICAO CHARACTER VARYING(255) NOT NULL,
  CEP CHARACTER VARYING(255),
  NUMERO CHARACTER VARYING(4),
  RUA CHARACTER VARYING(255),
  BAIRRO CHARACTER VARYING(120),
  CIDADE CHARACTER VARYING(120),
  UF CHARACTER VARYING(2),
  TELEFONE_FIXO CHARACTER VARYING(20),
  CONSTRAINT PK_DOMICILIOS PRIMARY KEY (ID)
) WITH (OIDS = FALSE);
ALTER TABLE PUBLIC.DOMICILIOS OWNER TO POSTGRES;

CREATE SEQUENCE PUBLIC.SEQ_DOMICILIOS
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE PUBLIC.SEQ_DOMICILIOS OWNER TO POSTGRES;