CREATE TABLE PUBLIC.PENDENCIAS
(
  ID INTEGER NOT NULL,
  I_PESSOAS INTEGER NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  DATA_PREVISTA_RESOLUCAO DATE NOT NULL,
  TIPO_PENDENCIA CHARACTER VARYING(1),
  DESCRICAO CHARACTER VARYING(255),
  CONSTRAINT PK_PENDENCIAS PRIMARY KEY (ID),
  CONSTRAINT FK_PESSOAS FOREIGN KEY(I_PESSOAS) REFERENCES PESSOAS(ID) ON DELETE CASCADE
) WITH (OIDS = FALSE);
ALTER TABLE PUBLIC.PENDENCIAS OWNER TO POSTGRES;
  
CREATE SEQUENCE PUBLIC.SEQ_PENDENCIAS
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE PUBLIC.SEQ_PENDENCIAS OWNER TO POSTGRES;