CREATE TABLE PUBLIC.PESSOAS_SITUACOES
( 
  ID INTEGER NOT NULL,
  I_PESSOAS INTEGER NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  SITUACAO CHARACTER VARYING(2),
  CONSTRAINT PK_PESSOAS_SITUACOES PRIMARY KEY (ID),
  CONSTRAINT FK_PESSOAS FOREIGN KEY(I_PESSOAS) REFERENCES PESSOAS(ID) ON DELETE CASCADE
) WITH (OIDS = FALSE);
ALTER TABLE PUBLIC.PESSOAS_SITUACOES OWNER TO POSTGRES;

CREATE SEQUENCE PUBLIC.SEQ_PESSOAS_SITUACOES
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE PUBLIC.SEQ_PESSOAS_SITUACOES OWNER TO POSTGRES;