CREATE TABLE PUBLIC.PESSOAS_DOMICILIOS
(
  ID INTEGER NOT NULL,
  I_PESSOAS INTEGER NOT NULL,
  I_DOMICILIOS INTEGER NOT NULL,
  RESPONSAVEL CHARACTER VARYING(1),
  CONSTRAINT PK_PESSOAS_DOMICILIOS PRIMARY KEY (ID),
  CONSTRAINT FK_PESSOAS FOREIGN KEY(I_PESSOAS) REFERENCES PESSOAS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_DOMICILIOS FOREIGN KEY(I_DOMICILIOS) REFERENCES DOMICILIOS(ID) ON DELETE CASCADE
) WITH (OIDS = FALSE);
ALTER TABLE PUBLIC.PESSOAS_DOMICILIOS OWNER TO POSTGRES;
  
CREATE SEQUENCE PUBLIC.SEQ_PESSOAS_DOMICILIOS
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE PUBLIC.SEQ_PESSOAS_DOMICILIOS OWNER TO POSTGRES;