/*------PESSOAS-----*/
CREATE OR REPLACE FUNCTION DBF_INSERE_SITUCAO_PESSOA_CADASTRADA() RETURNS TRIGGER AS 
$BODY$
  BEGIN
	INSERT INTO PESSOAS_SITUACOES (ID, I_PESSOAS, DATA_CADASTRO, SITUACAO) 
	VALUES((SELECT NEXTVAL('SEQ_PESSOAS_SITUACOES')), NEW.ID, CURRENT_DATE, 'C');
    RETURN NEW;
  END;
$BODY$ LANGUAGE PLPGSQL VOLATILE;

DROP TRIGGER IF EXISTS TIA_PESSOAS ON PESSOAS;

CREATE TRIGGER TIA_PESSOAS AFTER INSERT ON PESSOAS 
  FOR EACH ROW EXECUTE PROCEDURE DBF_INSERE_SITUCAO_PESSOA_CADASTRADA();

/*------PESSOAS_DOMICILIOS-----*/
CREATE OR REPLACE FUNCTION DBF_INSERE_SITUCAO_PESSOA_RELACIONADA() RETURNS TRIGGER AS 
$BODY$
  BEGIN
	INSERT INTO PESSOAS_SITUACOES (ID, I_PESSOAS, DATA_CADASTRO, SITUACAO) 
	VALUES((SELECT NEXTVAL('SEQ_PESSOAS_SITUACOES')), NEW.I_PESSOAS, CURRENT_DATE, 'R');
    RETURN NEW;
  END;
$BODY$ LANGUAGE PLPGSQL VOLATILE;

DROP TRIGGER IF EXISTS TIA_PESSOAS_DOMICILIOS ON PESSOAS_DOMICILIOS;

CREATE TRIGGER TIA_PESSOAS_DOMICILIOS AFTER INSERT ON PESSOAS_DOMICILIOS 
  FOR EACH ROW EXECUTE PROCEDURE DBF_INSERE_SITUCAO_PESSOA_RELACIONADA();

CREATE OR REPLACE FUNCTION DBF_INSERE_SITUCAO_PESSOA_NAO_RELACIONADA() RETURNS TRIGGER AS 
$BODY$
  BEGIN
	INSERT INTO PESSOAS_SITUACOES (ID, I_PESSOAS, DATA_CADASTRO, SITUACAO) 
	VALUES((SELECT NEXTVAL('SEQ_PESSOAS_SITUACOES')), OLD.I_PESSOAS, CURRENT_DATE, 'N');
    RETURN NEW;
  END;
$BODY$ LANGUAGE PLPGSQL VOLATILE;

DROP TRIGGER IF EXISTS TDA_PESSOAS_DOMICILIOS ON PESSOAS_DOMICILIOS;

CREATE TRIGGER TDA_PESSOAS_DOMICILIOS BEFORE DELETE ON PESSOAS_DOMICILIOS 
  FOR EACH ROW EXECUTE PROCEDURE DBF_INSERE_SITUCAO_PESSOA_NAO_RELACIONADA();

/*------PENDENCIAS-----*/
CREATE OR REPLACE FUNCTION DBF_INSERE_SITUCAO_PENDENCIA_ABERTA() RETURNS TRIGGER AS 
$BODY$
  BEGIN
	INSERT INTO PESSOAS_SITUACOES (ID, I_PESSOAS, DATA_CADASTRO, SITUACAO) 
	VALUES((SELECT NEXTVAL('SEQ_PESSOAS_SITUACOES')), NEW.ID, CURRENT_DATE, 'A');
    RETURN NEW;
  END;
$BODY$ LANGUAGE PLPGSQL VOLATILE;

DROP TRIGGER IF EXISTS TIA_PENDENCIAS ON PENDENCIAS;

CREATE TRIGGER TIA_PENDENCIAS AFTER INSERT ON PENDENCIAS 
  FOR EACH ROW EXECUTE PROCEDURE DBF_INSERE_SITUCAO_PENDENCIA_ABERTA();

  